### ISSUE TITLE
Compatibility with Python 3.13

### ISSUE THREAD

**Issue by amotl** [crate/croud#553]
Hi there,

when trying to use the package on Python 3.13,
```
$ python -V
Python 3.13.1
$ uv pip install croud
```

it croaks:
```
$ croud
Traceback (most recent call last):
  File "/Users/amo/dev/tmp/testdrive/.venv/bin/croud", line 5, in <module>
    from croud.__main__ import main
  File "/Users/amo/dev/tmp/testdrive/.venv/lib/python3.13/site-packages/croud/__init__.py", line 20, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

I think it has been fixed by that patch already, and just needs a release.
- GH-543

With kind regards,
Andreas.

**Comment by amotl** [comment]
It works. Thanks!

```bash
$ python -V
Python 3.13.1

$ croud --version
croud 1.13.0
```

**Comment by amotl** [comment]
`uvx` provides an even shorter entrypoint, if the package name equals the executable name.
```
$ uvx croud --version
croud 1.13.0
```

/cc @WalBeh
